# Generated by Django 3.2.4 on 2021-06-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
