# Generated by Django 3.2.4 on 2021-06-06 18:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='opinion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
